# Generated by Django 5.2.4 on 2025-07-14 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0002_category_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='Category',
            field=models.ManyToManyField(blank=True, to='Task.category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(blank=True, default='other', max_length=150, unique=True),
        ),
    ]
