# Generated by Django 5.2.4 on 2025-07-14 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0003_task_category_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
