# Generated by Django 5.2.4 on 2025-07-15 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0004_task_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(blank=True, choices=[('wr', 'Work'), ('pe', 'Personal'), ('st', 'Study'), ('de', 'Development'), ('he', 'Health'), ('fi', 'Finance'), ('other', 'Other')], default='other', max_length=150, unique=True),
        ),
    ]
